
from manim import *

class Scene11_Conclusion(Scene):
    def construct(self):
        # Color Scheme Definition
        background_color_hex = "#0A2342"  # Equivalent to dark_blue
        text_color_hex = "#FFFFFF"        # Equivalent to white
        # highlight_color_hex = "#FFFF00" # Equivalent to yellow (defined as per scheme, not explicitly used in this scene)

        self.camera.background_color = background_color_hex

        # Thank You Message Element
        thank_you_message = Text(
            "Thank You!",
            font_size=72,
            color=text_color_hex
        )
        # Position the thank you message slightly above the center
        thank_you_message.move_to(UP * 1.0)

        # Credits Element
        credits_lines_content = [
            "Thank you for watching",
            "This animation was generated by AI",
            "Powered by Manim"
        ]
        
        credits_mobject_group = VGroup()
        for line_content in credits_lines_content:
            credit_line = Text(line_content, font_size=30, color=text_color_hex)
            credits_mobject_group.add(credit_line)
        
        # Arrange credit lines vertically and position below the thank you message
        credits_mobject_group.arrange(DOWN, buff=0.4)
        credits_mobject_group.next_to(thank_you_message, DOWN, buff=0.8)

        # Animation Sequence
        # 1. Fade in the 'Thank You!' message
        self.play(FadeIn(thank_you_message, shift=UP * 0.5, run_time=1.5))
        self.wait(0.5) # Brief pause after thank you message appears
        
        # 2. Fade in the credits, with a slight stagger for each line
        self.play(FadeIn(credits_mobject_group, lag_ratio=0.25, shift=UP * 0.3, run_time=2.5))
        
        # 3. Hold the complete message (thank you + credits) for a few seconds
        self.wait(3.5)

        # 4. Fade out all elements together, fulfilling the 'FadeOut' animation type from the prompt
        all_scene_elements = VGroup(thank_you_message, credits_mobject_group)
        self.play(FadeOut(all_scene_elements, run_time=1.5))
        
        # 5. Final pause before the scene concludes
        self.wait(1)
